[package]
name = "xfade-gui"
version.workspace = true
description = "Xfade GUI"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version = "1.77.2"

[lib]
name = "xfade_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
xfade-core = { path = "../../core" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "net", "time"] }
reqwest = { workspace = true }
tauri = { version = "2.11.3", features = ["tray-icon"] }
tauri-plugin-log = "2"
tauri-plugin-autostart = "2"
tauri-plugin-shell = "2"

[dev-dependencies]
tempfile = "3"
